package com.safee.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.safee.model.Employee;
import com.safee.repository.EmployeeRepository;
@Service
public class EmployeeSpringServices {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private EmployeeRepository employeeRepository;

	public void addEmployee(Employee employee) {
		// @ResponseBody means the returned String is the response, not a view
		// name
		// @RequestParam means it is a parameter from the GET or POST request

		employeeRepository.save(employee);
	}

}
