package com.safee.service;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.safee.controller.EmployeeController;
import com.safee.model.Employee;
import com.safee.repository.EmployeeRepository;

@Service
public class EmployeeSpringServices {
	private static final Logger logger = LoggerFactory.getLogger(EmployeeSpringServices.class);
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private EmployeeRepository employeeRepository;

	public void addEmployee(Employee employee) {
		// @ResponseBody means the returned String is the response, not a view
		// name
		// @RequestParam means it is a parameter from the GET or POST request

		employeeRepository.save(employee);
	}

	public Employee readEmployee(Long employeeId) {
		logger.debug(employeeId.toString());
		return employeeRepository.findOne(employeeId);// findByEmployeeNo(employeeId);
	}
	/*
	 * public void updateEmployee(Employee employee) { employeeRepository. }
	 */
}
